# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f583ce4f61400e7e61649da7ecacb6ec6b44a4f77e7528fd47daefd285ed138ef1f5686f2d15eb1de45114c585a76abf48705be26c9fbe7ade0515c5aaa45a22

test:
  secret_key_base: 29629c6d970ad31888087d35244d824c703d37361039885768a202a5dbb1d9b992fd4139bcf4fc77a6b690bdc2add5a05673753c1f83e76b1d0687bdf18e831f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
